var text = document.querySelector('.text');
var percent = document.querySelector('.percent');
var progress = document.querySelector('.progress');
var count = 4;
var per = 16;
var loading = setInterval(animate, 50);
var number;


function animate(){
  if(count == 100 && per == 400){
    text.textContent = "Completed";
    text.style.fontSize = "70px";
    text.classList.add("add");
    clearInterval(loading);
    per = per + 4;
    count = count + 1;
    window.location='QR.html';
  }else{
    per = per + 4;
    count = count + 1;
    progress.style.width = per + 'px';
    percent.textContent = count + '%';
  }
}
let popup = document.getElementById("popup");

    function openPopup(){
        popup.classList.add("open-popup");
    }
    function closePopup(){
        popup.classList.remove("open-popup");
    }
let pic = document.getElementById("pic");

    function closePic(){
        pic.classList.add("close-pic");
    }

    let dic = document.getElementById("dic");

    function toy(){
      document.getElementById("output").innerHTML =
      Math.floor(Math.random() * 6) + 1;
    }
    
  function getRandomImage() {
      //declare an array to store the images
      var randomImage = new Array();
      
      //insert the URL of images in array
      randomImage[0] = "1.jpg";
      randomImage[1] = "2.jpg";
      randomImage[2] = "3.jpg";
      randomImage[3] = "4.jpg";
      randomImage[4] = "5.jpg";
      randomImage[5] = "6.jpg";
      
      //generate a number and provide to the image to generate randomly
      var number = Math.floor(Math.random()*randomImage.length);
      
      //return the images generated by a random number
      return document.getElementById("result").innerHTML = '<img src="'+randomImage[number]+'" />';
      }
      
      let hel = document.getElementById("hel");

      function openHelp(){
          hel.classList.add("open-hel");
      }
      function closeHelp(){
          hel.classList.remove("open-hel");
      }
